"""Cursor pagination per AIP-158.

Tokens are opaque to clients but happen to be base64url-encoded JSON
``{"offset": int}``. Keeping them opaque means we can switch to a different
cursor shape later without breaking clients that round-trip the token.

The per-resource list response shape (``{<plural>: [...], nextPageToken: ...}``)
is generated by :func:`list_response_model`, which names the items field
after the resource plural per AIP-132.
"""

import base64
import json
from dataclasses import dataclass
from typing import Annotated, Any

from fastapi import HTTPException, Query
from pydantic import BaseModel, Field, create_model

from ..schemas._base import SCHEMA_CONFIG


DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 1000


@dataclass(frozen=True)
class PageParams:
    """Validated page-size + page-token pair."""

    page_size: int
    offset: int


def _encode_token(offset: int) -> str:
    payload = json.dumps({"offset": offset}, separators=(",", ":")).encode("utf-8")
    return base64.urlsafe_b64encode(payload).rstrip(b"=").decode("ascii")


def _decode_token(token: str) -> int:
    """Decode a token into an offset.

    Raises ``HTTPException(400)`` on malformed tokens — we never want a bad
    token to surface as a 500.
    """
    if not token:
        return 0
    try:
        padding = "=" * (-len(token) % 4)
        payload = base64.urlsafe_b64decode((token + padding).encode("ascii"))
        data = json.loads(payload.decode("utf-8"))
        offset = int(data["offset"])
    except (ValueError, KeyError, TypeError) as e:
        raise HTTPException(
            status_code=400,
            detail={
                "error": {
                    "code": 400,
                    "status": "INVALID_ARGUMENT",
                    "message": "Invalid page_token",
                    "details": [{"reason": str(e)}],
                }
            },
        ) from e
    if offset < 0:
        raise HTTPException(
            status_code=400,
            detail={
                "error": {
                    "code": 400,
                    "status": "INVALID_ARGUMENT",
                    "message": "page_token offset must be non-negative",
                    "details": [],
                }
            },
        )
    return offset


def page_params(
    page_size: Annotated[int, Query(ge=1, le=MAX_PAGE_SIZE)] = DEFAULT_PAGE_SIZE,
    page_token: Annotated[str | None, Query()] = None,
) -> PageParams:
    """FastAPI dependency parsing ``?page_size&page_token``."""
    return PageParams(
        page_size=page_size,
        offset=_decode_token(page_token) if page_token else 0,
    )


def paginate(items: list[Any], params: PageParams) -> tuple[list[Any], str | None]:
    """Slice ``items`` according to ``params`` and compute the next token.

    Callers pass the already-fetched list (e.g., everything matching the
    time-range filter); this function does the offset/limit arithmetic.
    """
    start = params.offset
    end = start + params.page_size
    window = items[start:end]
    next_token = _encode_token(end) if end < len(items) else None
    return window, next_token


_LIST_MODEL_CACHE: dict[tuple[str, type], type[BaseModel]] = {}


def list_response_model(
    plural: str,
    item_schema: type[BaseModel],
) -> type[BaseModel]:
    """Build (or fetch from cache) the per-resource list response schema.

    The generated schema is named ``<Plural>ListResponse`` and has two
    fields: ``<plural>: list[item_schema]`` (the items, named per AIP-132)
    and ``next_page_token: str | None`` (aliased to ``nextPageToken``).
    Cached by ``(plural, item_schema)`` so multiple call sites share one
    type — important so FastAPI's OpenAPI generator emits one schema.
    """
    key = (plural, item_schema)
    cached = _LIST_MODEL_CACHE.get(key)
    if cached is not None:
        return cached

    model = create_model(  # type: ignore[call-overload]
        f"{item_schema.__name__}ListResponse",
        __config__=SCHEMA_CONFIG,
        **{
            plural: (
                list[item_schema],  # type: ignore[valid-type]
                Field(default_factory=list),
            ),
            "next_page_token": (
                str | None,
                Field(default=None, alias="nextPageToken"),
            ),
        },
    )
    _LIST_MODEL_CACHE[key] = model
    return model
